GET http://localhost:5295/games

###
GET http://localhost:5295/games/1

###
POST http://localhost:5295/games
Content-Type: application/json

{
    "name": "csGO",
    "genre": "FPS",
    "price": 24.33,
    "releaseDate": "2024-10-04"
}

###
PUT http://localhost:5295/games/3
Content-Type: application/json

{
    "name": "RISK",
    "genre": "coop",
    "price": 19.99,
    "releaseDate": "1992-07-15"
}

###
DELETE http://localhost:5295/games/1


